# Generated by Django 2.2.1 on 2021-07-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Блог'},
        ),
    ]
